title: <p align="center"> Pragadeesh S </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  <a href="docs/Pragadeesh_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/pragadeesh-s-12560b120/">LinkedIn</a> |
  <a href="https://github.com/spragad">GitHub</a>
  
  <br>   
  I'm working on Big Data, Spark, Machine learning & AI related projects.
  Worked with Big Data ETL from real-time data.
  Working in Data Engineering domain for 3 years.
  
  
  
  <br>
  </p>



theme: jekyll-theme-minimal
