#!/bin/sh

set -e

bundle exec jekyll build
HTMLProofer.check_directory('./_site', http_status_ignore: [999]).run
bundle exec rubocop -D 
bundle exec script/validate-html
gem build jekyll-theme-minimal.gemspec
